# Docker Compose конфигурация для RSS PoC Loader Connector
# Этот файл определяет сервис коннектора и его настройки

services:
  # Основной сервис RSS PoC коннектора
  rss-poc-connector:
    # Сборка образа из локального Dockerfile
    build: .
    
    # Настройки логирования с ротацией через 24 часа
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"
    
    # Переменные окружения для конфигурации коннектора
    environment:
      # =============================================================================
      # ОСНОВНЫЕ НАСТРОЙКИ OPENCTI
      # =============================================================================
      
      # URL адрес OpenCTI платформы (может быть localhost, IP или домен)
      - OPENCTI_URL=http://opencti:8080
      # API токен для аутентификации в OpenCTI (получить в разделе Settings -> Access)
      - OPENCTI_TOKEN=648cbcbf-91ab-433f-a062-107eccb9292b
      
      # =============================================================================
      # ПАРАМЕТРЫ КОННЕКТОРА OPENCTI
      # =============================================================================
      
      # Уникальный идентификатор коннектора (UUID) - должен быть уникальным
      - CONNECTOR_ID=c3eac7bd-3672-4aec-9d56-7ef44fc77785
      # Отображаемое имя коннектора в OpenCTI интерфейсе
      - CONNECTOR_NAME=RSS PoC Loader Connector
      # Область действия: какие типы объектов может создавать коннектор
      - CONNECTOR_SCOPE=Artifacts, Tools, Vulnerabilities
      # Уровень детализации логов: debug, info, warning, error
      - CONNECTOR_LOG_LEVEL=info
      # Интервал выполнения коннектора (ISO 8601 формат: PT10M = 10 минут)
      - CONNECTOR_DURATION_PERIOD=PT10M # 10 minutes interval

      # =============================================================================
      # ДОПОЛНИТЕЛЬНЫЕ ПАРАМЕТРЫ КОННЕКТОРА (ОПЦИОНАЛЬНО)
      # =============================================================================
      
      # Максимальное количество элементов в очереди перед остановкой
      - CONNECTOR_QUEUE_THRESHOLD=500
      # Запуск и завершение: False = работает постоянно, True = завершается после обработки
      - CONNECTOR_RUN_AND_TERMINATE=False
      # Отправка данных в очередь OpenCTI: True = включено, False = отключено
      - CONNECTOR_SEND_TO_QUEUE=True
      # Отправка данных в директорию: False = не используется
      - CONNECTOR_SEND_TO_DIRECTORY=False

      # =============================================================================
      # СПЕЦИФИЧНЫЕ ПАРАМЕТРЫ RSS КОННЕКТОРА
      # =============================================================================
      
      # URL RSS-ленты с PoC репозиториями GitHub
      - RSS_URL=https://poc-in-github.motikan2010.net/rss/
      # Интервал проверки RSS-ленты в секундах (600 = 10 минут)
      - RSS_CHECK_INTERVAL=600
      # Максимальное количество попыток при ошибках RSS
      - RSS_MAX_RETRIES=3
      # Задержка между повторными попытками в секундах
      - RSS_RETRY_DELAY=60
      # Количество RSS записей для обработки при старте (bootstrap режим)
      - RSS_BOOTSTRAP_COUNT=10
      # Максимальный размер файла для обработки в байтах (50MB)
      - RSS_MAX_FILE_SIZE=52428800
      # Минимальный размер файла для обработки в байтах
      - RSS_MIN_FILE_SIZE=10
      # Уровень TLP маркировки: red, amber, green, white
      - RSS_TLP_LEVEL=red
      
      # =============================================================================
      # НАСТРОЙКИ ЛОГИРОВАНИЯ
      # =============================================================================
      
      # Путь к файлу логов коннектора
      - CONNECTOR_LOG_FILE=/opt/opencti-rss-connector/connector.log
      # Интервал ротации логов в секундах (86400 = 24 часа)
      - CONNECTOR_LOG_ROTATION_INTERVAL=86400
      
      # =============================================================================
      # НАСТРОЙКИ МЕТРИК И МОНИТОРИНГА
      # =============================================================================
      
      # Включение метрик для мониторинга производительности
      - CONNECTOR_EXPOSE_METRICS=true
      # Уровень детализации метрик: basic, detailed, full
      - CONNECTOR_METRICS_LEVEL=detailed
      # Интервал обновления метрик в секундах
      - CONNECTOR_METRICS_UPDATE_INTERVAL=60
      
      # =============================================================================
      # НАСТРОЙКИ КЕША И ОЧИСТКИ
      # =============================================================================
      
      # Максимальный возраст записей кеша в днях (по умолчанию 30)
      - RSS_CACHE_MAX_AGE_DAYS=30
      # Максимальный размер кеша (количество записей)
      - RSS_CACHE_MAX_SIZE=1000
      # Включение автоматической очистки кеша
      - RSS_CACHE_AUTO_CLEANUP=true
    
    # Автоматический перезапуск контейнера при сбоях или перезагрузке системы
    restart: always
    
    # Сетевые настройки
    networks:
      # Подключение к внешней сети docker_default (должна существовать)
      - docker_default

# =============================================================================
# СЕТЕВЫЕ НАСТРОЙКИ
# =============================================================================
networks:
  # Внешняя сеть, к которой должен быть подключен контейнер
  # Эта сеть должна существовать в Docker (обычно создается OpenCTI)
  docker_default:
    external: true
