# Конфигурация RSS PoC Loader Connector для OpenCTI
# Этот файл содержит все настройки для работы коннектора

# =============================================================================
# НАСТРОЙКИ OPENCTI ПЛАТФОРМЫ
# =============================================================================
opencti:
  # URL адрес OpenCTI платформы (может быть localhost, IP или домен)
  url: 'http://opencti:8080'
  # API токен для аутентификации в OpenCTI (получить в разделе Settings -> Access)
  token: '648cbcbf-91ab-433f-a062-107eccb9292b'

# =============================================================================
# ОСНОВНЫЕ ПАРАМЕТРЫ КОННЕКТОРА
# =============================================================================
connector:
  # Уникальный идентификатор коннектора (UUID)
  id: 'c3eac7bd-3672-4aec-9d56-7ef44fc77785'
  # Тип коннектора: EXTERNAL_IMPORT - для импорта внешних данных
  type: 'EXTERNAL_IMPORT'
  # Отображаемое имя коннектора в OpenCTI интерфейсе
  name: 'RSS PoC Loader Connector'
  # Область действия: какие типы объектов может создавать коннектор
  scope: 'Artifacts, Tools, Vulnerabilities'
  # Уровень детализации логов: debug, info, warning, error
  log_level: 'info'
  # Интервал выполнения коннектора (ISO 8601 формат: PT10M = 10 минут)
  duration_period: 'PT10M' # 10 minutes interval
  # Максимальное количество элементов в очереди перед остановкой
  queue_threshold: 500
  # Запуск и завершение: False = работает постоянно, True = завершается после обработки
  run_and_terminate: 'False'
  # Отправка данных в очередь OpenCTI: True = включено, False = отключено
  send_to_queue: 'True'
  # Отправка данных в директорию: False = не используется
  send_to_directory: 'False'

# =============================================================================
# НАСТРОЙКИ NVD API (National Vulnerability Database)
# =============================================================================
nvd_api:
  # Максимальное количество попыток получения данных CVE при ошибках
  max_retries: 3
  # Базовая задержка между попытками в секундах (экспоненциально увеличивается)
  base_delay: 2
  # Минимальная задержка между запросами к NVD API (соблюдение rate limit)
  request_delay: 5 

# =============================================================================
# НАСТРОЙКИ RSS КОННЕКТОРА
# =============================================================================
rss_connector:
  # URL RSS-ленты с PoC репозиториями GitHub
  rss_url: 'https://poc-in-github.motikan2010.net/rss/'
  # Интервал проверки RSS-ленты в секундах (600 = 10 минут)
  check_interval: 600 # seconds
  # Максимальное количество попыток при ошибках RSS
  max_retries: 3
  # Задержка между повторными попытками в секундах
  retry_delay: 60 # seconds
  # Количество RSS записей для обработки при старте (bootstrap режим)
  bootstrap_count: 10
  # Максимальный размер файла для обработки в байтах (50MB)
  max_file_size: 52428800 # 50MB in bytes
  # Минимальный размер файла для обработки в байтах
  min_file_size: 10 # bytes
  # Уровень TLP маркировки: red, amber, green, white
  tlp_level: 'red'

  # =============================================================================
  # ФИЛЬТРЫ ИСКЛЮЧЕНИЯ ФАЙЛОВ
  # =============================================================================
  
  # Расширения файлов, которые НЕ будут обрабатываться
  excluded_extensions:
    # Изображения
    - ".png"
    - ".jpg"
    - ".jpeg"
    - ".gif"
    - ".bmp"
    - ".svg"
    - ".ico"
    - ".webp"
    - ".tiff"
    # Видео файлы
    - ".mp4"
    - ".avi"
    - ".mov"
    - ".wmv"
    - ".flv"
    - ".mkv"
    - ".webm"
    # Аудио файлы
    - ".mp3"
    - ".wav"
    - ".flac"
    - ".aac"
    - ".ogg"
    - ".wma"
    # Документы
    - ".pdf"
    - ".doc"
    - ".docx"
    - ".xls"
    - ".xlsx"
    - ".ppt"
    - ".pptx"
    - ".odt"
    - ".ods"
    - ".odp"
    - ".rtf"
    - ".csv"
    # Конфигурационные файлы
    - ".yml"
    - ".yaml"
    - ".xml"
    # Логи и временные файлы
    - ".log"
    - ".tmp"
    - ".bak"
    - ".swp"
    - ".swo"
    - ".orig"
    - ".rej"
    - ".patch"
    # Документация
    - ".md"
    - ".txt"
    - ".rst"
    - ".adoc"
    # Веб файлы
    - ".html"
    - ".htm"
    - ".css"
    - ".scss"
    - ".less"

  # Паттерны имен файлов (без расширения), которые НЕ будут обрабатываться
  excluded_file_name_patterns:
    - "readme"           # README файлы
    - "license"          # Лицензии
    - "copying"          # Копирование
    - "changelog"        # История изменений
    - "changes"          # Изменения
    - "contributing"     # Руководство по участию
    - "code_of_conduct"  # Кодекс поведения
    - "security"         # Безопасность
    - "notice"           # Уведомления
    - "authors"          # Авторы
    - "maintainers"      # Поддерживающие
    - "support"          # Поддержка
    - "funding"          # Финансирование
    - "pull_request_template"  # Шаблон pull request
    - "issue_template"   # Шаблон issue
    - "gitignore"        # Git ignore файлы

  # Имена директорий, которые НЕ будут обрабатываться
  excluded_dir_names:
    - ".git"             # Git репозиторий
    - ".github"          # GitHub специфичные файлы
    - "node_modules"     # Node.js зависимости
    - "__pycache__"      # Python кеш
    - "dist"             # Дистрибутивы
    - "build"            # Сборка
    - "vendor"           # Вендорные файлы
